### ISSUE TITLE
BUG: download file doesn't work for LaTeX (Firefox 79.0)

### ISSUE THREAD

**Issue by pretentious7** [sagemathinc/cocalc#4778] opened 2020-08-03 22:30 UTC
![Screenshot from 2020-08-03 18-25-16](https://user-images.githubusercontent.com/29604460/89233156-094d1700-d5b7-11ea-96c5-622f51df7148.png)

The download file button (depressed in screenshot) does not pop up a download file dialog.

Cocalc ver is most recent cocalc-docker ver. (don't really know how to check it)

**Comment by williamstein** [comment] 2020-08-03 22:45
I can confirm the following:

 - the download button both at the top of a file and in the files listing (so off to the right) appears to not work in Firefox with a pdf.
 - the download button works fine with pdf's in the latest version of Chrome.
 - clicking the checkbox in the file listing, then clicking the big "Download" button at the top in Firefox also does nothing visible with a pdf.
 - clicking the checkbox in the file listing, then clicking the download URL at the top in Firefox does work to open the PDF (you have to type control+s to save).
 - checking the network debugger when doing the above in Firefox shows that that PDF **is** being downloaded.  It's just that Firefox is weirdly not doing anything with it. 

This is something weird and special to how Firefox is handling pdf files.   With firefox it seems you can download any other filetype (as far as I can tell) by clicking the download button.

**Comment by williamstein** [comment] 2020-08-03 22:48
Another workaround or data point is that if you switch to the "PDF (native)" view of the document, then the download in there works fine:

![image](https://user-images.githubusercontent.com/1276278/89234369-af415700-d5a0-11ea-8356-63dd47e9cf84.png)

**Comment by DrXyzzy** [comment] 2020-08-04 06:40
Another data point: I don't see the problem at all with FF 79.0 on macOS 10.15.5. The download button in the CoCalc "PDF (preview)" frame, the Files list far-right download button, and the Files list checkbox / download dialog - all give a normal browser save dialog and create a local pdf file.

I have these options set in FireFox:
- **Downloads:** Always ask
- **Applications:** Content type: Portable Document Format; Action: Save File

<img width="973" alt="ff-pdf-save" src="https://user-images.githubusercontent.com/528072/89260185-64036480-d5f1-11ea-8b04-32d979a2def7.png">

**Comment by williamstein** [comment] 2020-08-04 15:25
@DrXyzzy I changed the Action to PDF for firefox for me to "Save file" from "Open in Firefox" and indeed it immediately started working fine too:

![image](https://user-images.githubusercontent.com/1276278/89312323-fde80300-d62b-11ea-8b04-d96ff6c7d98f.png)

I'm going to close this issue.  It's just that Firefox has some really unfortunate defaults, I guess.

**Comment by williamstein** [comment] 2020-10-25 18:46
I'm closing because:

- No complaints in a few months.
- I just tried changing the option to "Open in Firefox" and suddenly it works properly. 

So.... I think this was a Firefox bug that got fixed.  If not, re-open.

**Closed by williamstein** 2020-10-25 18:46 UTC
Labels: A-firefox, I-bug
