### ISSUE TITLE
make code in Jupyter markdown cells not executable by default

### ISSUE THREAD

**Issue by DataScienceUWL** [sagemathinc/cocalc#8085] opened 2024-12-30 17:24 UTC
I often include code in markdown cells inside assignments and I don't want students to be able to execute that code (I just want formatting and syntax highlighting for display).

Students end up markdown embedded code and don't understand why the results don't persist in their notebook when they close and reopen it.  

Please consider making markdown embedded code not executable by default.

**Comment by williamstein** [comment] 2024-12-30 19:00
Dupe of #7193

**Closed by williamstein** 2024-12-30 19:00 UTC

**Comment by williamstein** [comment] 2024-12-30 19:03
and yes we definitely will do this soon.
