### ISSUE TITLE
Changing Tab Size While Rapidly Closing File Tabs In CoCalc

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#6759] opened 2023-06-02 19:01 UTC
Opinion: I think it would be a more efficient (and enjoyable) user experience to have the file tabs remain the same size for a short duration of time while rapidly exiting out of files. 

They are currently dynamic, which is great since fewer tabs mean I can read more of each title, but perhaps they could become dynamic after a very short period of time (i.e. a few seconds) so while rapidly closing you do not need to readjust the mouse. 

(Ex. try quickly exiting out of 10+ tabs in Google Chrome and see how they change size afterward). I feel it should be more like this.

**Comment by williamstein** [comment] 2023-06-02 19:20
This is already implemented, **as long you don't move the mouse**.  If you close a file tab and don't move your mouse, the tab sizes do not change until you move your mouse.

The chrome UI is also not based on time, but on moving the mouse.  However, they make it so you have to move the mouse out of the entire tab area, whereas in cocalc, just moving the mouse a little causes the tabs to resize.

There's one other related big problem, which is that if you close a tab off to the right (say the last tab) in cocalc, then the whole tab scroll position changes, which prevents closing tabs after that one.  However, if you're closing a bunch of tabs and you start with an early tab, then it's fine since no scrolling happens.  Unfortunately, making any change to this behavior could be extremely difficult, since it's caused by the antd implementation of tabs.   The one thing we could do is completely get rid of scrolling tabs, and just have the tabs get really small as you add more of them, like chrome, and how cocalc used to be.  With the new sidebar functionality harald just added this week, combined with "recent files" or even a "tab sidebar", maybe this is the best way to move forward.

**Closed** 2023-06-05 23:35 UTC
