### ISSUE TITLE
Jupyter widgets not displayed in classic jupyter notebook

### ISSUE THREAD

**Issue by apurvasv** [sagemathinc/cocalc#6465] opened 2023-02-20 23:00 UTC
Error message:
A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.

**Comment by williamstein** [comment] 2023-02-20 23:10
What happens when you run the appropriate cells?  

Also, you need to provide the exact input, etc., so that somebody else can reproduce this problem.

**Comment by williamstein** [comment] 2023-03-09 05:07
Closing due to being too vague.

**Closed by williamstein** 2023-03-09 05:07 UTC
Labels: I-bug, A-jupyter, VAGUE-make-more-precise, E-unclear, A-ipywidgets
