### ISSUE TITLE
projects: Cannot read property 'save_all_files' of undefined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3765] opened 2019-04-22 10:49 UTC
chrome: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`

smc_git_rev: 102fc19a0a586c0b4557af63ab9bb5124228f24e

Date: 2019-04-20 14:21:09.732079

`Cannot read property 'save_all_files' of undefined`

```
TypeError: Cannot read property 'save_all_files' of undefined
    at https://cocalc.com/static/smc-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:5:351985
    at https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:302158
    at ft.__iterate (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:295557)
    at i.__iterateUncached (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:302127)
    at le (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:275651)
    at i.Y.__iterate (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:274482)
    at i.forEach (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:319523)
    at https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:293326
    at ft.Be.withMutations (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:286223)
    at ft [as constructor] (https://cocalc.com/static/0-682e2964cdf20a77bb6f.cacheme.js?682e2964cdf20a77bb6f:6:293285)
```

---

top frame obfuscated:

```
set_project_open(t,n)
{var r;if(je(this,e),-1===(r=ke.get("open_projects")).indexOf(t))
return this.setState({open_projects:r.push(t)})}
set_project_closed(t){var n,r;if(je(this,e),-1!==(n=(r=ke.get("open_projects")).indexOf(t)))
return ye.removeProjectReferences(t),
this.setState({open_projects:r.delete(n)})}
save_all_files(){je(this,e),ke.get("open_projects")
.filter(e=>this.redux.getProjectActions(e).save_all_files())} <<<<<<<<<<<<<<<<<
async have_project(t) [...]
```

**Comment by haraldschilly** [comment] 2019-12-12 15:17
Saw this again, this time with a different stacktrace, though

smc_git_rev: f6c2b808fb33e4f821c8619f23944a1dac84e9d2

Date: 2019-12-12 05:21:26.224319

`Cannot read property 'save_all_files' of undefined`

```
TypeError: Cannot read property 'save_all_files' of undefined
    at https://cocalc.com/static/smc-8c7a000bbca72f763500.cacheme.js?8c7a000bbca72f763500:5:1899265
    at e._wrapper.e._wrapper (https://cocalc.com/static/smc-8c7a000bbca72f763500.cacheme.js?8c7a000bbca72f763500:5:700722)
    at https://cocalc.com/static/smc-8c7a000bbca72f763500.cacheme.js?8c7a000bbca72f763500:5:702224
```

**Comment by williamstein** [comment] 2020-08-05 19:48
duplicate of #4789

**Closed by williamstein** 2020-08-05 19:48 UTC
Labels: A-webapp, I-bug, stacktrace
