### ISSUE TITLE
sync: Uncaught TypeError: Cannot read property 'merge' of undefined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4362] opened 2020-02-04 14:09 UTC
This happend for a sagews file, but since this is in `smc-util/sync/table/synctable.ts` it might be more general...

---

chrome: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

smc_git_rev: f0b7fdccf6d67ca37a8cbb2ef16082d779723556

Date: 2020-02-03 16:16:41.460064

`Uncaught TypeError: Cannot read property 'merge' of undefined`

```
TypeError: Cannot read property 'merge' of undefined
    at t.handle_new_val (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:544585)
    at t.update_change (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:543649)
    at t.changefeed_on_update (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:532105)
    at t.s.emit (https://cocalc.com/static/0-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:6:1707355)
    at t.handle_update (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:1537064)
    at Object.cb (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:1536747)
    at Object.cb (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:1495315)
    at cb (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:1474925)
    at e.handle_json_data (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:1471658)
    at e._handle_data (https://cocalc.com/static/smc-4e832cac519cdf73384f.cacheme.js?4e832cac519cdf73384f:5:1472398)
```

**Comment by williamstein** [comment] 2020-02-18 19:53
Dupe of #4383

**Closed by williamstein** 2020-02-18 19:53 UTC
Labels: A-sagews, A-sync, I-bug, stacktrace
