### ISSUE TITLE
it is extremely confusing to add a new payment method without making a purchase (for new accounts)

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3181] opened 2018-09-13 22:31 UTC
Seen while talking a new user through paying for a course:

- create a new account
- click Account and Subscriptions/Course Packages
- there is no way to add a payment method until CoCalc and Stripe sync - the button is disabled

Workaround: if a CoCalc admin locates the new user with the Admin tab and uses Stripe sync, the Add Payment Method is enabled.

**Comment by williamstein** [comment] 2018-09-14 00:00
That's really, really weird!  This is almost certainly a major, major new bug.   I think you must be wrong, as this really makes no sense.

**Comment by williamstein** [comment] 2018-09-14 00:09
I am closing this, since I just tried and what you claim is simply not true.   If you can clarify what the problem is, please re-open this.

What is true -- and this is very intentional -- is that you can't add a payment method until you select the item you want to purchase.  But the moment you make that selection, you can then add a payment method.  

Stripe sync is, by the way, a no-op on accounts that do not have a payment method already added, which is a further reason why this ticket makes no sense to me.

**Comment by williamstein** [comment] 2018-09-14 00:13
Oh, John just explained that the issue is **really** "there is no way to **ONLY** add a payment method without making a purchase".  Before you could simply click "Add payment method", but John completely removed all of that functionality in revamping our checkout flow to be first "say what you want to buy, then enter your card".   Now that this is clear, I agree that this is a very serious regression.

**Comment by williamstein** [comment] 2018-09-14 00:14
Also, a user can definitely add a payment method, but they have to:
1. choose to purchase something
2. enter their card info
3. click cancel.

At that point they will have their card in the system and everything is exactly like it used to be.

**Comment by DrXyzzy** [comment] 2018-09-14 02:44
Maybe *post hoc* fallacy, but while I was on the phone with a purchasing agent, she created a new account and the Add Payment Method button was disabled. This was puzzling to me, because I had been working on tutorials and expected it to be available, but change by @johnjeng explains it and I did not suggest choosing a subscription to enable the button. I clicked the Stripe sync button in Admin, and moments later, she was able to add payment method. AFAIK, the customer had not chosen a product, although I did not see her screen. In fact, the very next thing she asked was what to order. In this case, the subscription required was not among the available choices, but we were able to proceed using a custom invoice.

**Comment by DrXyzzy** [comment] 2019-08-01 19:39
Reminder (mainly to @DrXyzzy) that a **Stripe Invoice** may be better for purchasing agent purchases:
1. Add purchasing agent to Stripe as customer if not already there.
1. Billing > Invoices > New.
1. Line item description(s) and amount can be free text, i.e. don't have to come from list of products.

**Comment by johnjeng** [comment] 2019-09-25 15:33
@williamstein has since fixed this. 

@DrXyzzy **Stripe Invoice** is still best practice for a purchasing agent since otherwise they have to make an account.

**Closed by johnjeng** 2019-09-25 15:33 UTC
Labels: A-billing, I-bug, P-high
