### ISSUE TITLE
Feature Request: Ability to see two things (notebooks, documents, etc) side-by-side

### ISSUE THREAD

**Issue by flutefreak7** [sagemathinc/cocalc#4923] opened 2020-10-08 16:08 UTC
It would be very useful to be able to see two notebooks (or applications) side-by-side, but was disappointed to realize that the multi-pane functionality is currently limited to seeing different views of a single file or application.

Common workflows might be looking at 2 notebooks at the same time, looking at a notebook while typing in a Markdown or Latex document, etc

Ideas:

1. Add file-switching somehow to the view dropdown where one can select between Notebook, TOC, raw, etc, so any view in an existing set of panels can be any document
2. Add an additional layer of windowing
     - Suggestion: Enable tabs to be moved to a right-side pane (Notepad++ for example only supports left and right panes, not full paneling, and it's mostly fine)
3. Recommend users who want this to simply use their OS / browser to view multiple CoCalc tabs simultaneously
     - This almost certainly mean notebook cells can't be drag-and-dropped between tabs - Markdown, etc, can be copy-pasted back and forth thanks to system clipboard

**Comment by williamstein** [comment] 2020-10-08 19:07
Dupe of #4924

**Closed by williamstein** 2020-10-08 19:07 UTC

**Comment by flutefreak7** [comment] 2020-10-08 19:49
So sorry - I got a browser error and thought my post didn't go through - sorry for the noise!
