### ISSUE TITLE
add pari jupyter kernel

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1709] opened 2017-02-22 14:55 UTC
https://github.com/jdemeyer/pari_jupyter

**Comment by slel** [comment] 2017-07-21 20:49
Closing as duplicate of #160.

**Closed by slel** 2017-07-21 20:49 UTC
Labels: A-backend, A-jupyter, I-enhancement

**Comment by slel** [comment] 2017-07-21 20:52
For reference, the PARI Jupyter kernel is now hosted at
https://github.com/jdemeyer/pari_jupyter
and it can be installed on CoCalc by following the instructions there,
with slight changes which William will now describe.
