### ISSUE TITLE
tab away from task and back causes task editor to ignore "i" to enter vim input mode

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2758] opened 2018-03-16 21:58 UTC
1. Set Editor keyboard bindings to Vim and refresh browser.
1. Open a task file and have some other file open in the project.
1. Start editing a task.
1. While in Vim input mode (cursor is vertical bar), select tab for another CoCalc file.
1. Select tab to return to task file being edited.
1. Notice that cursor has moved to start of line and changed to block cursor (Vim edit mode), and typing "i" does not get into Vim input mode.
1. Workaround is to click outside the task being edited, then click back into the text to edit. At that point, typing "i" puts editor into Vim input mode.

**Comment by williamstein** [comment] 2018-03-16 22:02
This is actually not the root cause (i.e., ticket title is misleading).  The real problem is defocusing the task in vim mode doesn't switch back to rendered mode (it stays in codemirror edit mode).  This is because the command bar in vim also defocuses codemirror.  The fix for this bug is to code the editor entirely if both the command mode and codemirror editor loose focus.

This should be easy for me to fix.  Thanks for the report!

**Closed** 2018-03-19 02:12 UTC
Labels: A-tasks, I-bug
