### ISSUE TITLE
project info: modal's don't close

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4962] opened 2020-10-23 14:56 UTC
I just noticed that the modal's in the project info dialog don't close. this did work, but now it stopped? so, some update must have caused this. I think it has something to do with placing the modal inside a button – which is somehow retriggered with the close. The solution is probably to put the root of the modal element outside the button or something like that.

**Comment by williamstein** [comment] 2020-10-23 15:58
This is very likely caused by me upgrading antd to the latest version.

**Comment by williamstein** [comment] 2020-10-23 15:59
I think the fix is to not render the modal at all when it isn't visible, rather than rendering it as non-visible.  That's what I did for the project-wide modal (for starting projects), and it worked.

**Comment by williamstein** [comment] 2020-10-23 16:00
I'm labeling this a blocker, since this is VERY annoying -- I just tested this and now I have to refresh my browser.  I can probably fix this pretty easily...

**Comment by haraldschilly** [comment] 2020-10-23 16:03
ok, I was just trying to come up with something … I checked what's going on in the DOM, and it's either a bug or some bad CSS interfering.

**Comment by williamstein** [comment] 2020-10-23 16:07
I definitely think it's some sort of bug or compat issue with antd + rest of cocalc.  I'm just suggesting a workaround, rather than fixing the root cause.  I'll likely do that workaround but leave this ticket open and you can try to figure out the root cause.

**Comment by haraldschilly** [comment] 2020-10-23 16:07
oh and interesting, you did update antd to 4.7.0 ? but that's the one where I had so many issues. I started to revive this branch today, with 4.7.2: https://github.com/sagemathinc/cocalc/pull/4963/files

**Comment by williamstein** [comment] 2020-10-23 16:14
> oh and interesting, you did update antd to 4.7.0 ?

Yes, nearly a week ago.

> but that's the one where I had so many issues. 

Nope!  You had tons of issues with some version slightly **before** 4.7.0.  By upgrading to 4.7.0 the issue you had with "animation frames", which led to you doing worrisome stuff to try to workaround them... just went away.   

> I started to revive this branch today, with 4.7.2

Don't revive that branch.  Throw it away.  It was a massive amount of work to solve a dumb bug that was introduce in some point release of antd, then fixed in the next release.  That sort of approach is bad as I documented on your PR in github comments (namely -- you lose the typsecript info).

**Comment by haraldschilly** [comment] 2020-10-23 16:15
yes, I'm removing this part, the PR isn't finished.

I pushed a half-way done pr for this problem here.

**Comment by haraldschilly** [comment] 2020-10-23 16:28
ok, pr  #4964 ready for review

**Closed** 2020-10-23 16:35 UTC
Labels: A-webapp, I-bug, P-blocker
