### ISSUE TITLE
user-installed sage modules are not found in sagews with sage develop  v9.1.rc2

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4610] opened 2020-05-20 20:12 UTC
Reported by Samuel Lelièvre.

1. In a Linux terminal tab, do
    ```
    sage_select develop
    sage --pip install --user colorspacious
    ```
1. Again at the terminal, start command-line sage. Confirm the opening banner, the successful import, and the presence of the "/home/user/.local/lib/... directory in `sys.path`:
    ~$ sage
    ...
    │ SageMath version 9.1.rc2, Release Date: 2020-04-25                 │
    │ Using Python 3.7.3. Type "help()" for help.                        │
    ....
    | Warning: this is a prerelease version, and it may be unstable.
    ...
    sage: from colorspacious import cspace_converter
    sage:
    sage: sys.path
    ['',
     '/ext/sage/sage-dev/src/bin',
     '/ext/sage/sage-dev/local/lib/python37.zip',
     '/ext/sage/sage-dev/local/lib/python3.7',
     '/ext/sage/sage-dev/local/lib/python3.7/lib-dynload',
     '/home/user/.local/lib/python3.7/site-packages',
     '/ext/sage/sage-dev/local/lib/python3.7/site-packages',
     '/ext/sage/sage-dev/local/lib/python3.7/site-packages/IPython/extensions',
     '/home/user/.sage/ipython-5.0.0']
    sage:
1. Open a sage worksheet. Use "banner()" to verify the develop version of sage is running.
1. Observe that the same import that succeeded at the command line now fails:
    ```
    from colorspacious import cspace_converter
      ==>
    Error in lines 1-1
    ...
    ModuleNotFoundError: No module named 'colorspacious'
    ```
1. Observe that `sys.path` in the sagews does not include the local directory:
    ```
    sys.path
    ==>
    ['',
      '/ext/sage/sage-dev/local/lib/python37.zip', 
      '/ext/sage/sage-dev/local/lib/python3.7',
      '/ext/sage/sage-dev/local/lib/python3.7/lib-dynload',
      '/ext/sage/sage-dev/local/lib/python3.7/site-packages',
      '/cocalc/lib/python2.7/site-packages/', '.']
    ```

**Comment by DrXyzzy** [comment] 2020-05-20 20:24
Also, if you do `sage_select 9.0`, then restart the sage worksheet server and worksheet, the same worksheet does the import successfully and shows `/home/user/.local/lib/python3.7/site-packages` in sys.path.

**Comment by haraldschilly** [comment] 2020-06-18 15:48
I'm sorry, but dealing with tweaking sage for each dev release is too much work.
That's why I added "wontfix".
Rather, I propose we stop providing such dev builds altogether.
I've barely time to keep up with all the other software updates and I don't see much value in this.

I'll keep the ticket open, because "technically" this is the intended behavior of Sage. So, either accept that this is how it is or figure out how to tune/modify "something" to make this work for you in your case. I don't have time to investigate this.

**Comment by williamstein** [comment] 2020-06-19 07:28
Personally I think this is a bug in sage (upstream).

**Comment by williamstein** [comment] 2020-10-25 18:42
Closing since this is up to Harald.

**Closed by williamstein** 2020-10-25 18:42 UTC
Labels: A-sagews, I-bug, upstream, wontfix
