### ISSUE TITLE
admin upgrades are displayed incorrectly

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5036] opened 2020-11-25 20:46 UTC
Seen on macOS 10.15.6 with Chrome Version 87.0.4280.67 (Official Build) (x86_64) and Firefox 82.0.3 (64-bit).

- Create a project.
- Open project settings for the new project.
- Click "Admin Edit"
- Change "Shared CPU" from "1 cores" to "2 cores"
- Click "Done"
- Observe that project settings now shows 200 cores.

<img width="473" alt="cores-200" src="https://user-images.githubusercontent.com/528072/100279818-d98e9a00-2f2c-11eb-865e-5457b503b314.png">

Increasing Disk space and Shared RAM has similar effect, but it seems that only the feature most recently updated has the display error.

**Comment by williamstein** [comment] 2020-11-25 20:50
Is this only a *display* error?

**Comment by DrXyzzy** [comment] 2020-11-25 20:53
Yes afaik

**Comment by DrXyzzy** [comment] 2020-11-25 21:04
When any of the admin-upgraded values appears wrong in project settings, clicking "Admin Edit", and not doing anything else, i.e. not making any changes or saving, causes the display to appear correctly.

**Comment by haraldschilly** [comment] 2020-12-03 13:06
I'm reopening this, because the problem reported above is still there

![Screenshot from 2020-12-03 14-05-26](https://user-images.githubusercontent.com/207405/101021811-b25d4b80-3570-11eb-8d72-97cb17c3bd7e.png)

**Comment by haraldschilly** [comment] 2020-12-03 13:08
or well, maybe this should be a new ticket, I don't know. there are changes, but they have no impact on the problem I reported. What's correct in the two images above is that value "4" is for the admin upgrades. They effectively end up as much more (4gb I assume).

**Comment by williamstein** [comment] 2020-12-03 16:39
> I'm reopening this, because the problem reported above is still there

Maybe the database is "corrupted" for the specific project's settings that you're looking at?  Can you look?  The original bug would cause database to contain something in the settings table with a *string* value, instead of a number value.  I fixed the bug that caused that, but I didn't actually fix anything in the database itself.

**Comment by haraldschilly** [comment] 2020-12-03 17:24
oh ok, I see, I'll check

**Comment by williamstein** [comment] 2020-12-04 23:07
I'm closing this since I can't reproduce it.  I even tried manually setting a quota value to a string the database, which doesn't break anything as far as I can tell.  Maybe you just had a quota get set to something funny due to the bug before it was fixed?

**Closed by williamstein** 2020-12-04 23:07 UTC
Labels: A-frontend, I-bug
