### ISSUE TITLE
In chat message sent "time ago" does not update until a new message is sent

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#1548] opened 2017-01-19 04:50 UTC
Time ago used to be accurate in chats. Then someone added rendering restrictions that prevent time ago from being accurate.

**Comment by williamstein** [comment] 2017-01-19 05:01
Annoying to me -- so priority high!   but you're right that it is M-low.

**Comment by williamstein** [comment] 2017-05-03 04:54
I fixed this in my jupyter2 branch.  It was caused by TimeAgo changing their minPeriod parameter from seconds to ms...  so this will be fixed when I merge that later this week.

**Closed** 2017-05-29 18:38 UTC
Labels: A-sage chat, I-bug, M-low, P-high
