### ISSUE TITLE
Editing a license from the list of transactions open a disappearing pop up

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7005] opened 2023-10-25 17:59 UTC
There is a pop up window with license information on hover over the license in the transactions list. This is very nice and helpful. It is possible to click the edit button in it, which is also nice. BUT: it opens the edit dialog in the same pop up! The problem is that this dialog is quite big and does not fit on the screen. I cannot click the Cancel button because it is too high and if I try to scroll up, the whole pop up disappears. But when I hover over the license it appears (partially) again. A possible workaround is to drag the window to a bigger monitor ;-)

It would be nice if clicking on the edit button would switch to the regular editing page on the licenses tab, where scrolling works perfectly.

**Comment by williamstein** [comment] 2023-10-25 18:53
Duplicate of #6901

**Closed by williamstein** 2023-10-25 18:53 UTC
