### ISSUE TITLE
Install cling jupyter kernel for interactive C++

### ISSUE THREAD

**Issue by nthiery** [sagemathinc/cocalc#2324] opened 2017-08-24 16:15 UTC
[cling](https://root.cern.ch/cling) is a C++ interpreter based on clang/llvm. Would it be possible to install it on cocalc, together with its kernel?
I'll be using it for teaching C++ this coming semester. We will be using Jupyter locally on the university's machines, but having a backup solution on cocalc would be helpful!

@SylvainCorlay implemented a [Jupyter kernel implemented in C++](https://github.com/QuantStack/xeus-cling) which is more robust than the one provided by cling. And will soon enable widgets and plots!

Installation instructions with conda:

    conda install cling xeus-cling notebook -c QuantStack -c conda-forge

One should be able to install the kernel in another Jupyter deployment, but I haven't tried that.

**Comment by haraldschilly** [comment] 2017-08-24 17:04
Hello, I took a note for `cling` in anaconda, which will be installed in a future upgrade of cocalc.

I don't know how to install the jupyter kernels, so, I leave this for later ...

**Comment by nthiery** [comment] 2017-08-24 19:33
>    Hello, I took a note for cling in anaconda, which will be installed in
>    a future upgrade of cocalc.

Thanks Harald!

>    I don't know how to install the jupyter kernels, so, I leave this
>    for later ...

I have included some tentative instructions on the first comment to
install the kernels.

For reference: Sylvain Corlay & co are working on an improved kernel,
with upcoming supports for widgets, etc:

        https://github.com/QuantStack/xeus-cling

Apparently, the updated conda install scripts take care of installing
the kernels in Jupyter.

**Comment by nthiery** [comment] 2017-09-06 20:48
I have updated the installation instructions above.

**Comment by slel** [comment] 2017-09-06 22:39
About making Jupyter kernels from conda also work on a different Jupyter install,
maybe the discussion at the following StackOverflow answer helps?
https://stackoverflow.com/questions/39296020/how-to-install-sagemath-kernel-in-jupyter/41595015#41595015

**Comment by slel** [comment] 2017-12-07 15:05
There is demand for this feature. See for example this post from
last May on the Software Carpentry "discuss" mailing list:
http://lists.software-carpentry.org/pipermail/discuss/2017-May/005256.html
and the following discussion. Harald, have you had a chance to try the
instructions Nicolas provided in his edit to the first comment in this issue?
https://github.com/sagemathinc/cocalc/issues/2324#issue-252654327

**Comment by haraldschilly** [comment] 2017-12-07 15:25
Hmm, I don't remember, I've assigned this ticket to me and will update here when I have some progress.

**Comment by nthiery** [comment] 2018-02-01 13:31
Hi,
@slel forwarded me your exchange. I updated the installation instructions above. In a fresh miniconda install, nothing else is required: the kernels get installed automatically in the Jupyter of that miniconda's environment.

Now I don't know how cocalc's Jupyter setup works; maybe something additional is required to install it in Jupyter, if it lives outside of the conda environnement. Presumably something like running
```
      <cocalc>/bin/jupyter kernelspec install
```
from within the kernel directory `<conda-dir>/share/jupyter/kernels/xeus-cling-cpp11`.

Cheers,

**Comment by nthiery** [comment] 2018-02-01 13:34
I forgot to mention: if the install went well, `xeus-c++11` should appear in the notebook's list of available kernels. Trying:
```
    int i = 1;
    i+3
```
in a cell should be good enough to test it.

**Comment by haraldschilly** [comment] 2018-02-04 16:11
Hello, just a brief status update. All these Anaconda dependencies seem to start fighting with each other a little bit. Here is the issue with installing it right now:

```
$ conda install xeus-cling -c QuantStack -c conda-forge
Fetching package metadata ......................................................... 
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-fitdistrplus
  - r-irkernel
  - r-rematch
  - xeus-cling
Use "conda info <package>" to see the dependencies for each package.     
```

I'll see how it works without these R packages, and probably some follow up issues.

**Comment by haraldschilly** [comment] 2018-02-04 16:36
Ok, I think I am at the point where I failed last time, too. After removing r packages, it ends up here:

```
ERROR conda.core.link:_execute_actions(339): An error occurred while installing package 'QuantStack::gcc-7-7.2.0-1'.                                                                                                                   
LinkError: post-link script failed for package QuantStack::gcc-7-7.2.0-1                                                                                                                                                               
running your command again with `-v` will provide additional information                                                                                                                                                               
location of failed script: /ext/anaconda3/bin/.gcc-7-post-link.sh                                                                                                                                                                      
==> script messages <==
<None>

Attempting to roll back.


LinkError: post-link script failed for package QuantStack::gcc-7-7.2.0-1
running your command again with `-v` will provide additional information
location of failed script: /ext/anaconda3/bin/.gcc-7-post-link.sh
==> script messages <==
<None>

```

and the error itself is from some sanity check: `b"Installation failed: gcc is not able to compile a simple 'Hello, World' program.\n" `

**Comment by SylvainCorlay** [comment] 2018-02-04 16:44
@haraldschilly thanks for the details.

It would be awesome to see xeus-cling adopted in cocalc!

Quick question about your environment: which version of conda are you using? Someone else reported the post-link script failure earlier and we could not reproduce.

**Comment by slel** [comment] 2018-02-04 18:14
In a CoCalc terminal:

    $ /ext/anaconda3/bin/conda --version
    conda 4.3.33

**Comment by haraldschilly** [comment] 2018-02-04 18:24
@SylvainCorlay I have to add that I installed a lot into this anaconda environment and it didn't always went smooth. At some point in the future  (during summer) it will all be stashed away and reinstalled from scratch. Maybe that's all it needs, not sure. However, you can try to add your own anaconda environment in cocalc and compile it.  Here are some notes: https://github.com/sagemathinc/cocalc/wiki/Programming#anaconda-sage

**Comment by slel** [comment] 2018-02-04 19:30
The latest (64-bit Linux) Anaconda3 version available for download on the
[Anaconda download page](https://www.anaconda.com/download/#linux) is 5.0.1.

**Comment by slel** [comment] 2018-02-06 07:17
Okay, I made some progress.
- [installation instructions](https://cocalc.com/share/4711033a-b5d8-4fb3-9708-e9019ba1c158/Install-xeus-cling-in-CoCalc-project.md?viewer=share)
- [example worksheet](https://cocalc.com/share/4711033a-b5d8-4fb3-9708-e9019ba1c158/Try-xeus-cling-kernel-Jupyter-notebook-CoCalc.ipynb?viewer=share)

**Comment by SylvainCorlay** [comment] 2018-03-08 18:20
@slel @haraldschilly FYI, we have released `xeus-cling 0.2.2`, and now you can skip the "_Post-process the Jupyter kernels_" section in the document that @slel put together.

**Comment by SylvainCorlay** [comment] 2018-04-05 13:41
@slel hey, I noticed that the "post-process the Jupyter Kernel" section is still in the instructions document. Would you be ok with removing it now that the issue is fixed?

**Comment by slel** [comment] 2018-04-30 15:27
Thanks @SylvainCorlay for simplifying the installation process
by removing the need for this post-processing. I updated the
installation instructions.

**Comment by slel** [comment] 2018-04-30 15:36
@haraldschilly hey, I hope with the release of Ubuntu 18.04 this will
install seamlessly without conflicts with other installed packages.

**Comment by SylvainCorlay** [comment] 2018-05-25 10:59
@haraldschilly, btw, we have fixed the link issue that you were seeing on installation of xeus-cling.

Let me know if this works better if you get back to this!

**Comment by slel** [comment] 2018-08-23 03:29
@haraldschilly Now that CoCalc projects are based on Ubuntu 18.04,
could you try again to install these kernels system-wide?
The timing would be very good with JupyterCon this week (William's
talk about CoCalc is coming in a few hours), and the fall term coming.

**Comment by haraldschilly** [comment] 2018-08-23 12:39
I've searched via conda, and found a few bits and pieces. I could try installing the kernel, yes.

```
(base) /ext/anaconda5/lib$ conda list '.*xeus.*'
# packages in environment at /ext/anaconda5-py3:
#
# Name                    Version                   Build  Channel
xeus                      0.3.0                         0    conda-forge
(base) /ext/anaconda5/lib$ conda list '.*clang.*'
# packages in environment at /ext/anaconda5-py3:
#
# Name                    Version                   Build  Channel
clangdev                  3.9.1                   cling_4  [cling]  conda-forge
```

**Comment by SylvainCorlay** [comment] 2018-08-24 22:51
@harldschilly this version is very outdated and was very alpha-level work.

You need to install cling, xeus-cling and related channels from the QuantStack channel.

**Comment by SylvainCorlay** [comment] 2018-08-24 22:51
@haraldschilly this version is very outdated and was very alpha-level work.

You need to install cling, xeus-cling and related channels from the QuantStack channel.

**Comment by haraldschilly** [comment] 2018-08-30 18:13
Well, I just want to report some progress, such that nobody thinks this is a dead ticket :skull_and_crossbones: 

```
(base) salvus@25957896d5e0:/ext/anaconda5-py3$ conda install xeus-cling -c QuantStack -c conda-forge   
Solving environment: failed                                                                            
                                                                                                       
UnsatisfiableError: The following specifications were found to be in conflict:                         
  - gcc -> isl=0.12                                                                                    
  - xeus-cling                                                                                         
Use "conda info <package>" to see the dependencies for each package.                                   
```

I am not sure what this isl means, and no idea which package is requiring it. Do I have start a new separate anaconda install just for xeus? Or should I attempt to compile the code in the default python3 environment? I have to look closely at the dependencies.

**Comment by haraldschilly** [comment] 2018-09-01 16:40
ok, so, this looks like I have create a sub-environment in the global anaconda installation

**Comment by SylvainCorlay** [comment] 2018-09-01 16:44
Hey, I am back in Paris tomorrow. Would be happy to help troubleshoot the installation when back.

**Comment by haraldschilly** [comment] 2018-09-23 11:12
C++ 17 is now a jupyter kernel via xeus, using that idea of adding a nested environment. I don't know of any concrete use case, hence no idea if that's sufficient.

**Closed by haraldschilly** 2018-09-23 11:12 UTC
Labels: A-install

**Comment by slel** [comment] 2018-09-30 06:58
Would it make sense to also provide the C++ 11 and C++ 14 kernels from xeus?

**Comment by haraldschilly** [comment] 2018-09-30 11:09
Please don't ask me about C++ ;-)

I'm trying to avoid clutter and supporting the one with the highest version number seems to make sense for me.
