### ISSUE TITLE
cocalc becomes unresponsive on multifile latex documents

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3134] opened 2018-08-29 23:39 UTC
Steps to reproduce:

1. Clone [ENT](https://github.com/williamstein/ent)
2. Open `ent.tex` (this takes a moment, but works fine and gives a nice preview)
3. Open `body.tex`

Expected: A working latex editor (bonus: working preview).

Actual: It looks like its loading a preview, and the editor works for a moment, but soon the whole page stops responding.

**Comment by williamstein** [comment] 2019-11-04 04:19
Dupe of https://github.com/sagemathinc/cocalc/issues/904

**Closed by williamstein** 2019-11-04 04:19 UTC
