### ISSUE TITLE
crash (blank white page) during spellcheck

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5390] opened 2021-06-21 09:53 UTC
yet another white page crash

![Screenshot from 2021-06-21 11-52-26](https://user-images.githubusercontent.com/207405/122743390-3cf46680-d287-11eb-9739-4f3898823b3d.png)

**Comment by williamstein** [comment] 2021-06-21 21:24
Unfortunatley, there's probably no possible way I'll be able to reproduce or fix this as is, so marking it with VAGUE:

- "during spellcheck" **of what**?  What sort of document were you editing?
- Where are the underscores in the text on the left of your screenshot?  Weird.
- the c.fromTextArea error puzzles me, since everywhere that we use fromTextArea, it's `CodeMirror.fromTextArea` and I manually checked that CodeMirror is properly imported in all those cases.

**Comment by williamstein** [comment] 2021-06-21 22:00
Luckily, I just hit something that looks very similar in production when opening a markdown file.  It happened immediately on opening the file, before I could see anything.

For me, the actual crash is in the slate editor code, at line 207 of `src/smc-webapp/editors/slate/elements/codemirror.tsx`:

```ts
...

      cursorHandlers(options, editor, isInline);

      const cm = (cmRef.current = CodeMirror.fromTextArea(node, options));

      cm.on("change", (_, _changeObj) => {
        if (onChange != null) {
          onChange(cm.getValue());
        }
      });
...
```

One difference is that my traceback has nothing to do with spell checking, and neither does this code:

![image](https://user-images.githubusercontent.com/1276278/122832924-f3187a00-d2a0-11eb-8761-9a9748d5974d.png)

Honestly, this seems like a bug related to asynchronous loading, and maybe the Codemirror library doing something funny that is just incompatible with ES6 modules.   I workaround would be to load codemirror no matter what, rather than only when editing a file; this is pretty wasteful, since codemirror also involves a lot of styles/extensions/etc. so gets kind of big.  But for now it's likely a good move.  

We will likely switch to Codemirror 6, which is a total rewrite that is much more modern, and then would be a better time to lazy load codemirror.

**Comment by williamstein** [comment] 2021-06-21 22:12
I'm closing this and will push the early import of codemirror to production in a minute.  Reopen if this happens again (after refreshing your browser).

**Comment by haraldschilly** [comment] 2021-06-22 07:44
> "during spellcheck" of what? What sort of document were you editing?

I don't know, I guess one of the open files. the stacktrace says `update_misspelled_words`, that's why I assume it's during spellchecking. … and I have no idea why firefox doesn't show some of the underscores.

**Comment by haraldschilly** [comment] 2021-06-22 07:47
ok, yes, this is strange. as if codemirror isn't fully initialized? ok, I understand your attempt to fix this. I'l keep my eyes open if this happens again.

**Comment by haraldschilly** [comment] 2021-07-06 12:59
well, I just saw it again, and yes, when tabbing back to the slate editor. browser is FF 89.0.2. blank white page again. refreshing the page and it did load fine.

![Screenshot from 2021-07-06 14-56-48](https://user-images.githubusercontent.com/207405/124603969-c18bdb00-de6a-11eb-9683-7c5c17dd819d.png)

**Comment by williamstein** [comment] 2021-07-10 01:07
I just saw this when opening a Markdown file (uses slate).   Here is the context:
```
                        e.extraKeys.Right = function(e) {
                            r(e) || c.commands.goCharRight(e)
                        }
                        ,
                        e.extraKeys.Down = function(e) {
                            r(e) || c.commands.goLineDown(e)
                        }
                    }(w, O, x);
                    var n = _.current = c.fromTextArea(e, w);   <---- crashed here
                    n.on("change", (function(e, t) {
                        null != a && a(n.getValue())
                    }
                    )),
                    null != g && n.on("blur", g),
                    null != b && n.on("focus", b),
                    n.on("blur", (function() {
                        return N(!1)
                    }
                    )),
                    n.on("focus", (function() {
```

**Comment by williamstein** [comment] 2021-07-10 01:11
Line 207 of src/smc-webapp/editors/slate/elements/codemirror.tsx

**Closed** 2021-07-10 01:15 UTC
Labels: A-webapp, stacktrace
