### ISSUE TITLE
when re-returning assignments in a course, what's supposed to be going on?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2362] opened 2017-09-06 20:27 UTC
While working on https://github.com/sagemathinc/cocalc/pull/2357 I wasn't able to wrap my head around the logic in the store. Then I searched for bugs of my own. :thinking:  Then I tested it in prod ... :disappointed: 

Here is a screenshot with a returned assignment and two non-graded ones. Upon returning it again, it talks about **two** graded assignments?

Maybe there is some other problem (e.g. with the course file itself), but for now I'm leaving this issue here as a starting point for further investigations.

PS: also note, that as you can see, when I click on the red button, it re-returns the one which is already returned. That's ok (red for "overwriting"), but the labeling and the count is wrong.

![course-return-assignment-bug](https://user-images.githubusercontent.com/207405/30133116-e9fd2290-9352-11e7-9154-e196786c0657.png)

**Comment by haraldschilly** [comment] 2017-09-08 12:08
lowering priority. working with a fresh course file, this isn't reproducible. so, this must be caused by a broken course file or some weird edge case.

**Comment by williamstein** [comment] 2017-12-14 04:35
closing due to not being reproducible

**Closed by williamstein** 2017-12-14 04:35 UTC
Labels: A-course, A-webapp, E-unclear, I-bug, P-low
