### ISSUE TITLE
"Path Not Found" Shown When I Click the JupyterLab Button Above the File Explorer

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#7744] opened 2024-08-07 01:14 UTC
**Describe the bug**
I don't know if this is actually classified as a bug because everything works fine (as far as I can tell). The message says the path is being redirected. I just may not be technical enough to understand what is happening, but I find it confusing from a user perspective because there is no kind of reassurance that everything is okay (aside from the fact that I can see and use my files). 

**To Reproduce**
1. Go to https://cocalc.com/projects/0b8e4a77-555d-47e8-9512-9ff3375b25ee/files/
2. Click on the JupyterLab button above the File Explorer (1-click instance).
3. Notice the pop-up that says "Path Not Found".

**Expected behavior**
I would just prefer not to see the error if everything works fine.

**Screenshots**

<img width="1512" alt="Screenshot 2024-08-06 at 5 59 08 PM" src="https://github.com/user-attachments/assets/0f35c08c-3bb7-455f-8cf8-218dccef1a6b">

**Additional context**
Using Incognito and Google Chrome.

**Comment by williamstein** [comment] 2024-08-07 14:34
Dupe of #7717

**Closed by williamstein** 2024-08-07 14:34 UTC
