### ISSUE TITLE
sagews cell output that is quickly deleted reappears

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1852] opened 2017-04-12 10:22 UTC
1. Open sage worksheet.
1. Enter `n?` in a cell and click Run to see docstring.
1. Immediately (within a couple seconds of running the cell) click delete output button.
1. Wait a second or two and output reappears.

**Comment by williamstein** [comment] 2017-05-18 05:19
Heh -- this is caused by the code that ensures output appears even if the user closes their browser.  It makes perfect sense that this weird behavior would happen... Ugh.

**Comment by williamstein** [comment] 2024-08-29 00:42
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

**Closed** 2024-10-14 17:14 UTC
Labels: I-bug, wontfix, A-sagews, M-medium
