### ISSUE TITLE
course bug: adding collaborators to student projects

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2356] opened 2017-09-06 14:31 UTC
I'm hitting this which is blocking some important admin work.  Basically, I added myself as collaborator to a project, but something new is broken, so I don't get added to all the projects in a course when opening a .course file.  The console.log says this many times:
```
[9m32.92s Δ 9m17.5s] error setting time of project d63a5b9297f1ad30a to undefined -- 
RangeError: Invalid time value; please report to wstein@gmail.com
smc-79fcaf15b65ec05166e6.cacheme.js?79fcaf15b65ec05166e6:12 [9m32.93s Δ 0.01s] 
error setting time of project 9e584a5dbe955 to undefined -- RangeError: Invalid time 
value; please report to wstein@gmail.com
```

**Comment by johnjeng** [comment] 2017-09-12 12:43
Unable to reproduce. Closing per suggestion.

**Closed by johnjeng** 2017-09-12 12:43 UTC
Labels: A-course, I-bug, P-high
