### ISSUE TITLE
terminal in a frame empty after refresh

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5133] opened 2020-12-29 10:06 UTC
Quite frequently, a terminal in a frame editor (i.e. when I work with a .py file, where I have a terminal in a second frame) is blank when I refresh cocalc or open that file. I think it is triggered when the file opens, but before it is fully loaded I tab away to another file. But that's not always the case, though, but I think this triggers it with a high probability. This is also not new, I reported this before, but it happens much more frequently in the past few days.

I tried to reproduce this with a "pure terminal", but no luck. So, this is definitely for code-file + terminal only.

Also noteworthy: switching the terminal's view from terminal to source code and back to terminal loads it fine immediately. This is my current workaround.

**Comment by williamstein** [comment] 2020-12-29 16:53
There are several different renders for xterm.js:
  - DOM
  - canvas
  - WebGL

This might be a problem that would go away with using a different renderer (or just by upgrading xterm.js).  Right now we use the canvas renderer only.  This is configured in

smc-webapp/frame-editors/terminal-editor/connected-terminal.ts

When the problem happens, what exactly is going on with the DOM?  Given:

> I think it is triggered when the file opens, but before it is fully loaded I tab away to another file.

That sounds a lot like we just need to run some sort of "refresh" on the terminal a millisecond after it gets shown again, since maybe it measures the hidden DOM and decides to render at 0 height or something...

**Comment by williamstein** [comment] 2020-12-30 00:25
@haraldschilly 

1. Can you reproduce in a cc-in-cc dev environment?
2. Can you give 100% precise steps that result in reproducing this?

I ask because I tried with the file a.py containing
```
def f():
    print('hello')
```
and a terminal next to it:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1276278/103322267-5d3b1b00-49f2-11eb-9773-59180f76211f.png">

in cc-in-cc dev in both Safari and Firefox, trying both closing and opening and refreshing the page five times, and was not able to reproduce this problem even once.

Maybe it doesn't happen in dev mode?

Maybe it requires a high latency network connection?

**Comment by williamstein** [comment] 2020-12-30 00:28
And yes, I've seen this happen in production before recently, though I never saw any pattern or way to reproduce this. That's why I'm excited that you know how to reproduce it.

**Comment by williamstein** [comment] 2020-12-30 05:17
I just saw this in production and played around with the DOM (manually adding "abc" as a class, so I could grab it with equerry).  In this picture, the top left terminal appeared blank, the xterm stuff was off the screen in the upper left:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/1276278/103331457-e6fede80-4a1a-11eb-9bf6-00c1916e823e.png">

I then grabbed it with jQuery and moved it down and it appeared.  So the problem is that the canvas is strangely in the wrong position.  It is the right size and has the proper content, but it's position is wrong.

Resizing the frame immediately makes it "disappear" again off the top of the screen:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/1276278/103331511-27f6f300-4a1b-11eb-9742-fa6c8c087762.png">

**Comment by williamstein** [comment] 2020-12-30 05:27
I will work on this soon.  I think the first step is rewrite 

smc-webapp/frame-editors/terminal-editor/terminal.tsx

using a modern functional component, which will eliminate the unsafe deprecated lifecycle methods..

**Comment by haraldschilly** [comment] 2020-12-30 10:04
I just saw this in production, this time I don't think anything loaded – but the tab was in the background. In any case, the top position was positive. What was off is that all xterm divs had height zero. Then, I tried to set the height, in the end via `y.find('div').height(200)`, but nothing helped ... it stayed invisible as before.


![Screenshot from 2020-12-30 10-55-47](https://user-images.githubusercontent.com/207405/103344406-cd977a00-4a8e-11eb-9ed4-923e8ec18e8a.png)

![Screenshot from 2020-12-30 10-59-45](https://user-images.githubusercontent.com/207405/103344402-cc664d00-4a8e-11eb-979f-536bc076d23c.png)

![Screenshot from 2020-12-30 10-56-13](https://user-images.githubusercontent.com/207405/103344404-ccfee380-4a8e-11eb-864b-51df8fed2b09.png)

**Comment by williamstein** [comment] 2020-12-30 23:10
Good news -- I finished rewriting the temrinal using hooks.  It doesn't (of course) fix the terminal blanking bug.  However, I was able to reproduce this bug by following what Harald suggests above with a step thrown in (?).

1. As Harald said, make a file a.txt and a terminal to the right of it.
2. Open a.txt and *quickly* switch to the Find tab while it is opening.
3. A few seconds later, click on the a.txt tab.
4. This reproduces the bug for me 100% of the time.

**Closed** 2020-12-31 00:10 UTC
Labels: A-frame_editor, A-terminal, I-bug
