### ISSUE TITLE
Tab completion in Jupyter does not put cursor at end of line when refining the search

### ISSUE THREAD

**Issue by kevinywlui** [sagemathinc/cocalc#3050] opened 2018-08-05 19:30 UTC
To reproduce:
1. Start a new Jupyter notebook.
2. In the first cell, type Ab[Tab]e[Enter]
3. The cursor is now after the b instead of the end of line.

**Comment by haraldschilly** [comment] 2018-08-06 12:56
I tested this. First, I wasn't able to reproduce. Then, it became clear that it's crucial to do some refinement of the search by entering another character. It looks like entering one or more additional characters for the completion search sets the offset for advancing the cursor position too early (or sets it to 0). Once that was clear it's easy to reproduce.

**Comment by haraldschilly** [comment] 2018-08-07 12:00
@kevinywlui this should be fixed (maybe you have to refresh your cocalc tab in the browser to get the update).

**Closed by haraldschilly** 2018-08-07 12:00 UTC
Labels: I-bug, jupyter2
