### ISSUE TITLE
Fetch additional output is unexpected for progress indicators

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7664] opened 2024-07-05 03:51 UTC
![image](https://github.com/sagemathinc/cocalc/assets/1993227/3391d413-5783-4093-8a0c-7608da6c330e)
What happens (I guess) is that updating progress indicator generates a lot of output rewriting old lines, but from the user's perspective only a few lines are there. No idea how easy it is to implement a solution, but it would be nice not to click the button to see the progress.

**Comment by novoselt** [comment] 2024-07-05 03:55
Extra point - because I was clicking that button, the focus was on the cell with long computation. If I clicked Shift+Enter without noticing it, I would restart the long computation instead of using its result in the next cell.

**Comment by williamstein** [comment] 2024-07-05 16:09
this is probably related to https://github.com/sagemathinc/cocalc/issues/7164

**Comment by williamstein** [comment] 2024-07-24 16:28
Please provide a minimal reproducible example to greatly increase the chances of this getting fixed.

**Comment by williamstein** [comment] 2024-07-26 19:04
Closing this until it has proper input to be able to reproduce it.

**Comment by novoselt** [comment] 2024-07-27 04:46
```
for i in range(20000):
    print(i, end="\r")
```
For me this shows the button, with 100 000 there is a button and pressing it hangs the page for a bit. "The right solution" is probably not to show the whole output with carriage returns, but a "condensed version" that corresponds to the end result. The same for actually storing the output in the notebook.

**Comment by williamstein** [comment] 2024-07-27 04:52
Closing this again, until it has proper input to be able to reproduce it.  This is a ticket about progress indicators, but your example is showing how to make the Fetch Additional Output button appear...

**Comment by novoselt** [comment] 2024-07-27 05:01
Fair point, I just assumed that this is how progress indicators are implemented. This one shows the button for the 5th epoch for me:
```python
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import numpy as np

# Generate some dummy data
x_train = np.random.rand(100000, 10)
y_train = np.random.randint(2, size=(100000, 1))

# Create a simple model
model = Sequential([
    Dense(32, activation='relu', input_shape=(10,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=32)
```

**Comment by williamstein** [comment] 2024-07-27 05:02
> I just assumed that this is how progress indicators are implemented. 

What is "this"?

**Comment by williamstein** [comment] 2024-07-27 05:09
I see beautiful color output progress bars with your code, not the ascii art you showed:

<img width="866" alt="image" src="https://github.com/user-attachments/assets/9d19fb8b-aef0-4cff-940e-65a4352560fe">

It also completes now, since the "Fetch Additional Output" threshold is now really large.

Regarding "What happens (I guess) is that updating progress indicator generates a lot of output rewriting old lines" it's in fact a huge amount of output.  Running your code makes a large Jupyter notebook with 11,943 lines.

```sh
~/triage$ wc -l 7664.ipynb 
11943 7664.ipynb
```

**Comment by williamstein** [comment] 2024-07-27 05:13
This is all very annoying, because ipywidgets has very nice progress bars, which are extremely efficient. Look I have no clue what to do with this.  I mean any library can in theory output anything it wants, and that's not possible for us to control.  

The title of the ticket is "Fetch additional output is unexpected" in a situation where there's a huge amount of output. 

It sounds like what you really mean is: "I don't like the semantics of fetch additional output. I wish it worked more like vs code, where there's some truncation in the middle instead."   Fair point, but that's simply not what is implemented, and I also don't agree with that.

**Closed by williamstein** 2024-07-27 05:13 UTC
Labels: I-bug, A-jupyter, E-unclear, UX-user experience

**Comment by novoselt** [comment] 2024-07-27 05:17
This is what I see:
![image](https://github.com/user-attachments/assets/c0f912c4-b4da-4b3f-b801-20e25c5f02ca)
and I do think that this is important for those who use TensorFlow for long training, but I agree that it is not a big portion of users.

**Comment by williamstein** [comment] 2024-07-27 05:33
When did you last restart that project?

-- William Stein

**Comment by novoselt** [comment] 2024-07-27 05:49
Two weeks ago, restarting it does finish this example without buttons, but with 1,000,000 data points it appears on epoch 4. The notebook file size seems to stop growing unless I press the button, doing it after the run completed results in 3.6MB file.

But it still does not affect a lot of users, so not a high priority.
