### ISSUE TITLE
video does not play in modern jupyter notebook, plays normally in classic

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2740] opened 2018-03-09 23:30 UTC
Problem reported by Bill Page:

Upload [small.mp4](http://techslides.com/demos/sample-videos/small.mp4) - which is from [this page](http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5).

Then try this code cell in a Jupyter notebook with Anaconda 3 kernel:
```
%%HTML
<video width=400 controls>
  <source src="small.mp4" type="video/mp4">
</video>
```

With modern notebook, control appears, but video does not play. With Classic notebook under Plain Jupyter Server, video plays normally.

**Comment by haraldschilly** [comment] 2018-03-10 11:05
maybe #2725  ? although it's suspicious that it works in classic notebook.

**Comment by billpage** [comment] 2018-03-10 12:59
Explicit Jupyter code such as
```
from IPython.display import display, HTML
HTML(ani.to_html5_video())
```
injects HTML containing
```
<video width="1200" height="600" controls autoplay loop>
<source type="video/mp4" src="data:video/mp4;base64,AAAAHGZ0eXB ...
</video>
```
with embedded data. I think this is also what is generated implicitly if the plt is not closed. Is an embedded src handled the same way as an explicit file reference?

**Comment by haraldschilly** [comment] 2018-03-10 14:44
Ok, I see, cocalc's jupyter implementation should extract such embedded data.

**Comment by ashesh-0** [comment] 2020-03-03 09:33
It will help a lot if someone can share how to circumvent the issue if that is possible.
I'm generating video by concatenating images. I'm downloading the video everytime to play it locally.

**Comment by williamstein** [comment] 2020-03-03 15:45
I just tried precisely the originally reported error at the top of this issue and it worked fine:

![image](https://user-images.githubusercontent.com/1276278/75792486-e6c28380-5d22-11ea-9ea0-0a200015911a.png)

So I'm closing this issue, since video does play fine in the classical notebook.   @ashesh-0 you must be hitting a different issue.  Can you provide detailed steps so it can be reproduced in a new ticket?

**Closed by williamstein** 2020-03-03 15:45 UTC
Labels: A-jupyter, I-bug

**Comment by ashesh-0** [comment] 2020-03-03 16:24
I'm using jupyter lab. Maybe that could be the difference.

`Python 3.8.1`

Relevant packages
```
jupyter-client==5.3.4
jupyter-core==4.6.3


jupyterlab==1.2.6
jupyterlab-server==1.0.6
opencv-python==4.2.0.32
```
Code Cell1:
```
import os 
dirname = '/tmp2/ashesh/gaze360_data/imgs/rec_001/head/000001/'
fpaths = []
for fname in os.listdir(dirname):
    fpath = os.path.join(dirname,fname)
    fpaths.append(fpath)
fpaths.sort()
print([fp for fp in fpaths][:10])
```
Code Cell2:
```
import cv2
import numpy as np
import glob
 
img_array = []
size = None
for fpath in fpaths:
    img = cv2.imread(fpath)
    height, width, layers = img.shape
    if size is None:
        size = (width,height)
    else:
        img = cv2.resize(img,size)
    img_array.append(img)
 
 
out = cv2.VideoWriter('project.mp4',cv2.VideoWriter_fourcc(*'DIVX'), 4, size)
 
for i in range(len(img_array)):
    out.write(img_array[i])
out.release()
```
Code cell3:
```
%%HTML
<video width=400 controls>
  <source src="project.mp4" type="video/mp4">
</video>
```
![Screenshot from 2020-03-04 00-21-35](https://user-images.githubusercontent.com/6098025/75796119-284c4080-5dae-11ea-9d65-617097439bf3.png)

**Comment by williamstein** [comment] 2020-03-03 16:25
> I'm using jupyter lab.

Yes, JupyterLab and https://cocalc.com are completely different things.   You probably want to head over to https://github.com/jupyterlab/jupyterlab
