### ISSUE TITLE
allow Greek letter tab completion (as in Jupyter notebooks) in frame editor

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4050] opened 2019-08-30 18:09 UTC
Reported by Jack Lyle.

In a Jupyter notebook (for example with Julia 1.1 or Python system-wide kernels), if you type `\alpha<tab>` into a code cell, a Greek letter alpha is entered.

This does not happen with the frame editor for .jl or .py files. Consider adding it as a feature.

**Comment by williamstein** [comment] 2019-09-03 01:08
Some notes about:

> In a Jupyter notebook (for example with Julia 1.1 or Python system-wide kernels), if you type \alpha<tab> into a code cell, a Greek letter alpha is entered.

I have no clue how this works, and didn't know about this. It must be some sort of "clever hack" (abuse?) of the tab completion mechanism.  As a result, it is very flaky in CoCalc-Jupyter, though it seems to work well enough in Jupyter classic.   This is the sort of functionality that should (IMHO) be implemented on the client, but appears here to have been implemented as a hack in various kernels.... ?   Using the client will be more efficient too.

The upshot is that I should just implement this in the client browser, so the backend kernel never sees this.  I've already done *almost exactly this* client side for editing of `.lean` files.  Try typing `\alpha[space]` in a lean file and it'll change.  Using space makes more sense than tab (and it's what lean uses with vscode), but I could make either tab or space work...

**Comment by williamstein** [comment] 2019-09-03 01:09
I added the jupyter tag, since we should also redo how cocalc-jupyter does this.

**Comment by williamstein** [comment] 2024-07-24 22:51
I can confirm that today JupyterLab does this.  I can also confirm -- much to my surprise -- that CoCalc Jupyter does this as well.  Cool!  It must be entirely through the kernel via the backend, since I didn't  implement this ;-).  But works for me.  Closing.

**Closed by williamstein** 2024-07-24 22:51 UTC
Labels: A-jupyter, I-feature request, A-frame_editor
