### ISSUE TITLE
install pyensembl

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#220] opened 2015-11-02 23:17 UTC
Website: https://pypi.python.org/pypi/pyensembl

I attempted to "pip install pyensembl" with sage-6.9, and it crashes during the build.  This may be quite difficult; not sure.  

REQUESTED BY: Laurens Skelly

**Comment by haraldschilly** [comment] 2018-01-17 14:49
I lean towards closing this (and yes, I close it). The issue is that this also requires to download a global data directory for some genome reference data. I don't know which dataset is required. It's also from 2015. I'll look for the original request by Laurens Skelly.

**Closed by haraldschilly** 2018-01-17 14:49 UTC
Labels: A-install, I-software request, M-low, P-low
