### ISSUE TITLE
set environment variables for a project

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4523] opened 2020-04-18 18:30 UTC
There is no way to set environment variables that impact the entire docker container of a project.  You can set variables in ~/.bashrc that impact terminals, but nothing an earlier level in the process tree.

The point of this ticket is to add a configuration panel in Project settings where you can set such variables.   These would then get stored in the database and be pulled from the database and set at some point (how this happens would be implemented differently for the different ways cocalc runs, unfortunately -- **or** it would be done directly by local_hub.coffee ASAP, and hence impact that process and anything it spawns; the latter approach would be generic and easiest to implement, but possibly subject to race conditions).

We might also set something at the user account level, where the variables impact any project *they* start.  This would be sort of similar to account-wide ssh keys, versus project specific ssh keys.

REQUESTED BY: Oliver Schulz

**Comment by williamstein** [comment] 2020-04-18 18:30
This is related to https://github.com/sagemathinc/cocalc/issues/3929

**Comment by oschulz** [comment] 2020-04-18 18:37
Thanks for considering this, this would be very helpful!

**Comment by williamstein** [comment] 2020-04-18 18:40
Can you give an example of how you would use this, so we can make sure it is at least flexible enough for your use case...?

**Comment by oschulz** [comment] 2020-04-18 18:43
A typical use case would be setting `$JULIA_NUM_THREADS` project-wide, depending on the number of (shared or dedicated) CPU cores assigned to that specific project.

**Comment by oschulz** [comment] 2020-04-18 18:45
It would be ideal if the env-variable would be set fairly early on in the project startup sequence, so that it would affect both CoCal notebooks and classic and JupyterLab notebook servers.

**Comment by williamstein** [comment] 2020-04-18 18:51
The tree typically looks like this:

![image](https://user-images.githubusercontent.com/1276278/79667481-de0afd00-816a-11ea-9e29-23ceb943ddcd.png)

and by setting the env in the local_hub.js process, it'll impact everything that spawns.

**Comment by oschulz** [comment] 2020-04-18 18:53
Sound good to me! :-)

**Comment by haraldschilly** [comment] 2020-04-18 18:56
I would also set this in `smc-project/local_hub`. for the kucalc environment, there is already a procedure to tune the env variables. My first thought would be an `--env` option, which you can give multiple times for setting `key:value` pairs right there or pass in all of them at once  (as a json string?). Then, it's a matter of strategically setting that `--env` option based on what's in the database. 

What remains is to define precedence. Should we allow any variable to be set? Or all but the ones prefixed with `COCALC_*` ? It's probably fine to just allow any variable and worst case, a project doesn't start.

**Comment by williamstein** [comment] 2020-04-18 19:05
> for the kucalc environment, there is already a procedure to tune the env variables.

If possible, I greatly prefer a solution that works across the six or so ways to run CoCalc, rather than having to implement something six different ways.  You're suggesting how to implement this in a kucalc specific way.   I really hope that is not necessary and that a generic solution is possible instead (I think it is).

**Comment by williamstein** [comment] 2020-04-18 19:06
> It's probably fine to just allow any variable and worst case, a project doesn't start.

Agreed, since it will be possible for users to disable this functionality at any time themselves and then their project will work again.

**Comment by DrXyzzy** [comment] 2020-06-07 22:24
Resolving this issue might help with the workaround published in jupyterlab/jupyterlab#4064 for lack of a *--user* install for [jupyterlab extensions](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html). The workaround is based on setting JUPYTERLAB_DIR before launching jupyterlab. This relates to a support ticket by Caio Machado regarding installing the "toc" jupyterlab extension.

**Comment by haraldschilly** [comment] 2020-06-20 20:07
this in project settings

![Screenshot from 2020-06-20 22-06-19](https://user-images.githubusercontent.com/207405/85210682-5ac08000-b342-11ea-81da-10a3773440d4.png)

causes

![Screenshot from 2020-06-20 22-06-41](https://user-images.githubusercontent.com/207405/85210684-614ef780-b342-11ea-846f-59124aac8731.png)

hence closing

**Closed by haraldschilly** 2020-06-20 20:07 UTC
Labels: A-project, I-enhancement, I-feature request

**Comment by mforbes** [comment] 2020-06-20 21:04
Are there plans for a user-level way of doing this as William initially suggested?  I am trying to find a way of setting the username for mercurial/git.  Currently I require collaborators to ssh in forwarding a variable [`LC_HG_USERNAME`](https://swan.physics.wsu.edu/forbes/public/notes/cocalc-workflow/#Setup) that they have set.  This obviously does not work if users try to run `hg` from the web interface, but I could do this through such user-level settings.  Not sure how the user-level settings would work when people ssh in though...

Maybe related: is `COCALC_USERNAME` ever set to something useful?  (It seems to be set to `'user'` whenever I check.)

**Comment by haraldschilly** [comment] 2020-06-20 21:08
@mforbes what is "user level"? The first screenshot in my comment is a panel in the project settings, which those who have access to the project can modify.

Ad 2: this will always match that bogus linux user. The problem is that there are multiple collaborators in the same terminal/environment. They share the same values. Maybe there is something else that can be done, but this is out of scope of that issue here.

**Comment by mforbes** [comment] 2020-06-20 21:11
@haraldschilly I mean "user account level": i.e. each user could have different values.  Ideally each user could set their own `LC_HG_USERNAME` variable so that whoever ran `hg commit` would have their name set.  This will allow me to identify who is running the command.

**Comment by oschulz** [comment] 2020-06-20 22:39
Thanks for the new feature!

**Comment by williamstein** [comment] 2020-06-20 22:59
Michael, harald implemented a solution to your problem:

1. Make a terminal named michael.term
2. Click the rocket ship icon at the top then add env vars in the file that
pops up.
3. Other people make their own .term files with their own customizations.

**Comment by mforbes** [comment] 2020-06-20 23:11
Thanks. (Had to check that it was not April 1st!) Unfortunately, it seems that we would need to do this with every project and every collaborator, adding a new file to every project any time we add a collaborator. If there were a way to do this through the user account settings, then we could just initialize each project once, and have each user set the variable once, then we would be done.

**Comment by williamstein** [comment] 2020-06-20 23:35
We could at least automate creation of a named term file (if it doesn't
exist) whenever a user opens a project....?

**Comment by mforbes** [comment] 2020-06-20 23:39
That would help, but account level variables would still be preferable (e.g. if someone runs `!hg commit -m "message"` in a notebook, or in the convenient terminal command window on the right etc.

**Comment by williamstein** [comment] 2020-06-21 00:33
Unfortunately, account level variables like you're describing don't make
sense in cocalc.  There is only one Linux user per cocalc project.
