### ISSUE TITLE
In Markdown view, scroll doesn't go to bottom of code view

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2269] opened 2017-08-09 08:06 UTC
In a Firefox window, the scroll-bar on the code view sometimes doesn't get to the bottom of the code (usually 3 lines are below the view).  They can be accessed using the arrow keys. 

I'm working on the exact means of replicating this, it doesn't always come up as a problem and once the cursor has been manually moved to the bottom with the arrow keys it seems to self correct

- Using latest cocalc docker image
- Firefox 54.0.1 on OS X 10.11.6

Note the strange rendering of the scroll widget (the image shows the bottom of the window)

![2017-08-09 06 07 21 pm](https://user-images.githubusercontent.com/415981/29111461-ad676a6a-7d2d-11e7-801f-187ad25553f3.png)

**Comment by haraldschilly** [comment] 2017-08-09 08:17
Hmm, looks like some calculation offset issue. Do you use any zoom? I.e. sometimes the browser has something else than 100% set to make the layout look larger. That info might help when we try to reproduce it...

**Comment by zeigerpuppy** [comment] 2017-08-09 08:31
I'm not using any zoom.
I can replicate it on first loading of any .md or .Rmd file.

Seems only to affect Firefox, same problem not present in Chromium v58.0.3029.110

**Comment by williamstein** [comment] 2017-09-06 19:45
Don’t put too much time into fixing this unless easy, since the whole editor will get rewritten using React.  It’s on the hit list.

**Comment by haraldschilly** [comment] 2020-06-19 18:16
closing. this particular code editor no longer exists.

**Closed by haraldschilly** 2020-06-19 18:16 UTC
Labels: A-firefox, A-markdown, I-bug, M-low, P-hal
