### ISSUE TITLE
Statement generation and emailing are fuzzy

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7158] opened 2024-01-01 03:44 UTC
For the account novoselt@gmail.com with an off compute server and therefore ongoing charge for its disk I was receiving daily statements, sometimes several times a day, and then stopped, from December 16. There is another one on December 26, when a subscription renewed. So it seems that preventing multiple emails resulted in no emails.

If I go to https://cocalc.com/settings/statements I can see all the daily statements, sometimes there are 2 of them on the same date and time, which makes no sense.

And if I look at monthly statements, there are also multiple ones on November 25 and December 25 without any clear system as to why there is a second one.

**Comment by williamstein** [comment] 2024-01-17 05:48
Dupe of https://github.com/sagemathinc/cocalc/issues/7068

**Closed by williamstein** 2024-01-17 05:48 UTC
Labels: I-bug, A-billing, P-high
