### ISSUE TITLE
safari: icons flash off briefly when mousing over toolbars

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2913] opened 2018-06-11 17:43 UTC
Seen with Safari Version 11.0.3 (13604.5.6) on macOS 10.13.3. Not seen with Chrome on same OS.

1. Start a CoCalc session, open a couple projects, and open a project with a couple files open.
1. Slide cursor horizontally across project toolbar, with no buttons down. Note that the icons flash off and back on as cursor moves into and out of a toolbar button.
1. Slide cursor horizontally across files toolbar and note the same thing.

**Comment by williamstein** [comment] 2018-06-11 18:03
Can you include a screenshot.  I don't really feel like I understand 1 or its relevance...

**Comment by DrXyzzy** [comment] 2018-06-11 19:54
Here's a video. It's too brief to capture a screenshot. Step 1 is only to get a few buttons for mousing across, probably not essential. Only happens if the Safari window has focus. In project toolbar, flash appears with project tabs but not with Account/Admin/CoCalc/Help

https://cocalc.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/ISSUES/issue2913_flicker.mp4?session=default

**Comment by williamstein** [comment] 2020-12-19 06:17
@DrXyzzy I cannot reproduce this.

**Comment by williamstein** [comment] 2020-12-20 17:16
Closing since I can't reproduce.  Open if you can.

**Closed** 2024-10-14 17:16 UTC
Labels: I-bug, A-safari, VAGUE-cannot-replicate, HEISENBUG - hard to reproduce
