### ISSUE TITLE
LLMs: paid should not be red

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7507] opened 2024-04-30 16:15 UTC
![image](https://github.com/sagemathinc/cocalc/assets/1993227/73aa8ed5-71a0-4c79-ae39-8e2c2ac3c2e8)

Red "paid" gives a subconscious impression that it is dangerous/bad/expensive, while it is pretty neutral - for CoCalc usage the price is likely to be very low and inconsequential. Instead of such clear distinction, how about we put the expected price in plain black regular font with the expected price in cents? For free models it would be "0¢" while for others "~1¢-4¢" (I would not use 0¢ as the lower bound ever - if the model is very cheap, show it as "~1¢-2¢", to convey that a) it is an approximate range and b) there is *some* charge.

**Comment by williamstein** [comment] 2024-04-30 16:22
I strongly agree with this.   In antd red is semantically "ERROR".    Also, in my mind "green is the color of money", so having green be free seems weird too.

**Comment by williamstein** [comment] 2024-04-30 16:24
>  how about we put the expected price in plain black regular font with the expected price in cents? 

I'm not sure how viable this is, because the expected price range depends on the input, and I think this model selector is often displayed before the input is decided on (or rather, the input can frequently be changed).

**Comment by novoselt** [comment] 2024-04-30 16:29
OK, this may be harder to implement, but how about not displaying price at all except for "0¢" for free models and "greying out" paid models for which the user does not have enough credit on the account? With some tooltip on how to top it up.

**Comment by williamstein** [comment] 2024-04-30 16:40
> OK, this may be harder to implement, but how about not displaying price at all except for "0¢" for free models and "greying out" paid models for which the user does not have enough credit on the account? With some tooltip on how to top it up.

I already put a lot of work into making it so that if you try to use an LLM and don't have enough credits to pay for it, then a modal pops up and asks you for those credits.  It's part of the workflow already.  Changing this to provide directions to go somewhere else then come back would be a usability regression IMHO.

**Comment by novoselt** [comment] 2024-04-30 16:44
Makes sense! Then I am just for a plain "0¢" marker on free models and nothing on paid ones. If a user selects a paid model, there should be an approximate price displayed next to the submission button.

**Comment by haraldschilly** [comment] 2024-04-30 17:32
> this may be harder to implement

I'm implementing exactly that estimate. I talked about this yesterday and as an example there is an estimated range for the AI tool in a cell. My plan is to add more. Throwing in a number that could be off by 10x feels wrong to me.

I don't know if that "1¢" is a good idea. Personally, I would be very confused if I see this. `$0.01` is what I have chosen.

Regarding the colors, there could be different ones, or none. I don't understand why this is perceived as an error. E.g. the default syntax highlighting shows each string is red, not implying they're all errors. Or closing an app in Mac OS is a red dot. Any interpretation depends on the context.

**Comment by williamstein** [comment] 2024-04-30 17:35
> I'm implementing exactly that estimate.

Awesome!  I bet it will be difficult so it is even more awesome that you're doing it!

I also like $0.01 instead of 1¢.

>  I don't understand why this is perceived as an error. 

See https://ant.design/components/tag

<img width="646" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/c03da0cb-382c-484f-b4d0-25e30b60fe0d">

and https://ant.design/components/alert:


<img width="602" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/d53efdf0-1b63-48ba-a050-723d7f42d785">

>  Or closing an app in Mac OS is a red dot.

That's because it is dangerous.

**Comment by novoselt** [comment] 2024-04-30 17:36
1¢ is two characters which are very easy to interpret, while $0.01 is five characters and one has to pay attention to the number of zeros and dot placement, especially when we are displaying high precision in some places. Since with LLMs we do have a good sense of scale, I think cents are very natural units. What do William and Blaec think?

**Comment by novoselt** [comment] 2024-04-30 17:37
OK, William also prefers dollars, that's perfectly fine!

**Closed** 2024-05-06 20:03 UTC
Labels: UX-user experience, AI, I-focus
