### ISSUE TITLE
wysiwyg Markdown editor displays warning for specific markdown sequence

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5262] opened 2021-04-05 19:33 UTC
The following steps cause **(WARNING: unable to find path to node. You might have to close and open this file.)** to appear in the wysiwyg Editable frame, using Chrome on macOS.  Refreshing the browser or closing and reopening the file clear the warning and render the markdown as expected. 

1. Open a new .md file. Keep the left pane in Source view and set the right pane to Editable. All text below is entered in the Source pane.
2. Copy the following text into your clipboard:
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse`
3. Type the following in and leave the cursor at the end of line 3, after "baz":
  <pre>
  - foo

  - baz
  </pre>
4. Move the cursor up one line, between the two lines already typed, and hit enter to make a new third line.
5. Type two spaces, a "*", and a space to start an unnumbered list.
6.  Paste in the _lorem ipsum_ text from the clipboard.
7.  Get the warning message.

![image](https://user-images.githubusercontent.com/528072/113617221-be8b0f80-961b-11eb-8fb3-89aa95c08f50.png)

8.  Refresh the browser and see rendered text:

![image](https://user-images.githubusercontent.com/528072/113617011-7a980a80-961b-11eb-9040-c6d06deefc8b.png)

**Comment by williamstein** [comment] 2021-04-05 20:03
Unfortunately, I cannot reproduce this.  I tried about 10 times in various ways, including both dev mode and production using Chrome on macOS.   Are you sure the steps are exactly as you say above, and nothing is ambiguous or different?   Can you do  it again being careful to follow what you say and record it?

**Comment by haraldschilly** [comment] 2021-04-06 08:48
I can't reproduce this either

**Comment by DrXyzzy** [comment] 2021-04-06 09:04
A few more data points, as noted in daily chat:
- I'm able to produce the bug reliably with both Standard and Vim editor keybindings.
- If I wait a few seconds between typing the space after the asterisk and pasting the _lorem ipsum_ text, the bug does not appear. If I paste the text immediately after typing the space after the asterisk, the bug appears most of the time.
- After I paste the text, a code-folding triangle appears left of line 1 just before the warning.

**Comment by williamstein** [comment] 2021-04-12 04:51
Closing this since that warning doesn't exist anymore in the code...   I'm sure there are still bugs in WYSIWYG markdown editing with slate, of course.

**Closed by williamstein** 2021-04-12 04:51 UTC
Labels: A-slate, HEISENBUG - hard to reproduce, I-bug
