### ISSUE TITLE
removing hidden jupyter file causes stall on reopen

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2693] opened 2018-02-09 12:24 UTC
1. Open new file1.ipynb with anaconda3 kernel.
2. Execute and run some code cell, e.g. `2+3`, and save notebook.
3. Click `Close and halt`.
4. In a .term, do
```
rm file1.ipynb .file1.ipynb.sage-jupyter2
```
5. Open Log view and try to open file1.ipynb. Tab opens for notebook and stalls on "Loading".

**Comment by williamstein** [comment] 2019-03-13 22:48
I can reproduce this bug exactly as you state, and it's still there after all the rewrites of things.

**Comment by williamstein** [comment] 2019-03-13 23:00
HORRIBLE WORKAROUND: Restart the project.

Probable fix -- when the file is deleted close the jupyter backend state.

**Comment by williamstein** [comment] 2020-10-27 06:47
This is fixed by the "deleted file awareness" code.  It's a little weird since the first time you re-open file1.ipynb it'll complain and close it. But the next time it asks you to undelete it and works properly.

**Closed by williamstein** 2020-10-27 06:47 UTC
Labels: A-jupyter, I-bug
