### ISSUE TITLE
Use SandDance as viewer for CSV-files?

### ISSUE THREAD

**Issue by oschulz** [sagemathinc/cocalc#4554] opened 2020-05-03 11:12 UTC
Just an idea - maybe CoCalc could use [SandDance](https://sanddance.js.org/) as an option to view CSV files? Since SandDance has a full JS API, I guess it could (in principle) be fully embedded.

**Comment by williamstein** [comment] 2020-11-03 01:17
This is a duplicate of #1644.

**Closed by williamstein** 2020-11-03 01:17 UTC
