### ISSUE TITLE
sync: ipynb set_cursor_locs → set → missing required set field time of table cursors

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3449] opened 2019-01-11 09:55 UTC
Saw this twice for ipynb files:

chrome: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36`

smc_git_rev: 98bd0518464576000dc1ab95ab884718b5e76a2e

Date: 2019-01-11 07:55:02.379678

`missing required set field time of table cursors`

```
Error: missing required set field time of table cursors
    at t.set (https://cocalc.com/static/smc-252ab2cee0f04e999fbd.cacheme.js?252ab2cee0f04e999fbd:5:671239)
    at t.set_cursor_locs (https://cocalc.com/static/smc-252ab2cee0f04e999fbd.cacheme.js?252ab2cee0f04e999fbd:5:1167952)
    at o (https://cocalc.com/static/1-252ab2cee0f04e999fbd.cacheme.js?252ab2cee0f04e999fbd:6:336452)
    at https://cocalc.com/static/1-252ab2cee0f04e999fbd.cacheme.js?252ab2cee0f04e999fbd:6:335931
    at function.e._wrapper.e._wrapper (https://cocalc.com/static/smc-252ab2cee0f04e999fbd.cacheme.js?252ab2cee0f04e999fbd:5:860333)
    at https://cocalc.com/static/smc-252ab2cee0f04e999fbd.cacheme.js?252ab2cee0f04e999fbd:5:861835
```

**Comment by williamstein** [comment] 2019-01-11 18:38
Also fixed via same commit as https://github.com/sagemathinc/cocalc/issues/3452.  The problem is much better type checking now, and the schema explicitly required time to be set, but the code used time not being set in some cases.

**Closed by williamstein** 2019-01-11 18:38 UTC
Labels: A-jupyter2, A-sync, stacktrace
