### ISSUE TITLE
embedded youtube video in sagews does not play correctly

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3208] opened 2018-09-26 12:35 UTC
Try either of the following in sagews cells. In the first case, a fraction of a second is shown. In the second, no video is displayed.
```
%md

<iframe width="560" height="315"
        src="https://www.youtube.com/embed/QMpkFde3euA"
        frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>
</iframe>
---
~~%md~~ [correction]
from IPython.lib.display import YouTubeVideo
YouTubeVideo('1j_HxD4iLn8')
```

This used to work, as noted by #14 in the Cocalc wiki page on [sagejupyter](https://github.com/sagemathinc/cocalc/wiki/sagejupyter#-question-what-kernel-features-are-supported-in-sage-worksheets)

Reported by Dominique SOUDIERE.

**Comment by haraldschilly** [comment] 2018-09-26 12:51
Hmm, I'm wondering if that markdown mode cell is really supposed to show a youtube video? This looks like some code for a "normal" python jupyter cell.

**Comment by DrXyzzy** [comment] 2018-09-26 12:58
Thank you for the correction. The second cell should not be markdown. That's my mistake in this issue.

The [original demo file](https://github.com/sagemathinc/cocalc-example-files/blob/master/sagews-jupyter/jupyter-python3.sagews) used a compute cell, used to work, and does not work now.

**Comment by williamstein** [comment] 2024-08-29 01:18
I can confirm that this is still broken exactly as you say.  However, I'm marking it wontfix; it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374 and will just use the normal Jupyter output rendering, which works fine.

WORKAROUND: use a Jupyter notebook

**Closed** 2024-10-14 17:14 UTC
Labels: I-bug, wontfix, A-sagews
