### ISSUE TITLE
deleting a project without upgrades appears to work, but really has no effect

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4193] opened 2019-10-25 03:31 UTC
Seen on macos 10.14.3 with Chrome Version 77.0.3865.120 (Official Build) (64-bit) and Safari Version 12.0.3 (14606.4.5). Found during front-end testing with Puppeteer.

1. Create a new project.
1. Open Settings. If the project has any upgrades, remove them using the "Adjust your upgrade contributions..." dialog by clicking "Remove all your upgrades from this project", then "Save changes".
1. Open project settings, click "Delete Project...", and click "Yes, please delete this project" to confirm.
1. Observe the red banner, "Warning: this project is deleted!"
1. Wait 5 seconds (just to rule out a timing problem).
1. Refresh your browser and notice that the red warning banner is gone. Open the Projects list and verify that the project is **not** deleted.

**Comment by williamstein** [comment] 2019-10-26 17:58
The problem is there is a missing call to save the changes to the projects table to the backend.  To see that this is the problem, do the above steps 1-4, then:

- 5. Open that above project again in another browser and see the project is not marked as deleted,
- 6. Change the title of the project in the first browser.
- 7. See in *both* browsers that the title changes and the deleted status ALSO changes... since now the fact that the project was deleted gets sent out.

Note that undelete project saves fine as does hide project...

**Closed** 2019-10-26 18:24 UTC
Labels: A-project, E-easy, I-bug
