### ISSUE TITLE
jupyter: closing frame twice leads to "erase_active_key_handler" crash

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5453] opened 2021-08-16 12:43 UTC
1. open a jupyter notebook, with just that notebook and no other frame opened
2. click twice on the "x" to close the frame in the top right

```
TypeError: Cannot read properties of undefined (reading 'erase_active_key_handler')
    at t.disable_key_handler (https://cocalc.com/static/67901ce97298dddf877b.js:1:7594)
    at t.blur (https://cocalc.com/static/67901ce97298dddf877b.js:1:8974)
    at L (https://cocalc.com/static/ee60e1a596d86ba3d663.js:1:40552)
    at dispatch (https://cocalc.com/static/app-f785242a5255d7fd7b2c.js?deb1761e5f638eff1ca6:2:2840698)
    at g.handle (https://cocalc.com/static/app-f785242a5255d7fd7b2c.js?deb1761e5f638eff1ca6:2:2838693)
    at e._wrapper.e._wrapper (https://cocalc.com/static/app-f785242a5255d7fd7b2c.js?deb1761e5f638eff1ca6:2:227514)
```

**Comment by williamstein** [comment] 2021-08-16 16:33
I'm glad you stumbled on this -- it's a really cool stress test of closing then opening... which pushes how rendering, etc. works.   After fixing the immediate issue, I used it to find some other related race conditions, which are ultimately caused by "lying" to typescript about whether or not an attribute is defined.

**Closed** 2021-08-16 16:34 UTC
Labels: A-jupyter, stacktrace, A-frame_editor
