### ISSUE TITLE
share: some reactjs exception

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2546] opened 2017-12-05 19:42 UTC
this happened today in a hub-share:

> Component(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

original:

```
Invariant Violation: Minified React error #152; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=152&args[]=Component for the full message
or use the non-minified dev environment for full errors and additional helpful warnings.", "stack": "Invariant Violation: Minified React error #152; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=152&args[]=Component for the full message or use th
e non-minified dev environment for full errors and additional helpful warnings.
    at Error (native)
    at w (/cocalc/src/smc-hub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:9:16)
    at ya (/cocalc/src/smc-hub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:25:9)
    at za (/cocalc/src/smc-hub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:26:13)
    at a.render (/cocalc/src/smc-hub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:29:26)
    at a.read (/cocalc/src/smc-hub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:29:25)
    at b._read (/cocalc/src/smc-hub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:13)
    at b.Readable.read (_stream_readable.js:54:25)
    at resume_ (_stream_readable.js:54:25)
    at _combinedTickCallback (internal/process/next_tick.js:54:1)
    at process._tickCallback (internal/process/next_tick.js:76:9)
```

**Comment by williamstein** [comment] 2017-12-06 05:41
I'm closing this because it happened I think for a few minutes yesterday, I noticed it, and fixed it already.  Is it happening again? 

This was caused by some refactor of the code by @johnjeng moving a method to be a "functional component" in another file, and me not testing the PR sufficiently.

**Closed by williamstein** 2017-12-06 05:41 UTC
Labels: A-share or publish, stacktrace
